---
apiVersion: v1
kind: Namespace
metadata:
  name: tools-prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: tools-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ideal-customer-profile-mapper
  namespace: tools-prod
  labels: { app: icp}
spec:
  replicas: 1
  selector:
    matchLabels: { app: icp}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: { app: icp }
    spec:
      nodeSelector: 
        kubernetes.io/hostname: hetzner-s0
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: ideal-customer-profile-mapper
          image: ghcr.io/kolchurinvv/ideal-customer-profile-mapper:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests: { cpu: 50m, memory: 128Mi }
            limits:   { cpu: 500m, memory: 512Mi }
          readinessProbe:
            httpGet: { path: /login, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /login, port: 3000 }
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              value: "file:/app/data/heart.db"
            - name: BETTER_AUTH_URL
              value: "https://icp.kolchurin.dev"
            - name: ADMIN_EMAILS
              valueFrom:
                secretKeyRef:
                  name: icp-admin-emails
                  key: icp-admin-emails-list
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: better-auth-secret
                  key: better-auth-secret-val
          volumeMounts:
          - name: heart-data
            mountPath: /app/data
      volumes:
      - name: heart-data
        persistentVolumeClaim:
          claimName: local-path-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: icp-service
  namespace: tools-prod
spec:
  selector: { app: icp }
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icp
  namespace: tools-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: icp.kolchurin.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: icp-service
                port:
                  number: 3000
